### PR TITLE
chore: Remove bluefin things

### LINKED ISSUE #20: Begin removing bluefin things
- [x] Disable Bluefin Builds: https://github.com/ublue-os/bluefin/commit/0c4000045cd369009127b4bb238f62ce3bc66841
- [ ] Remove bluefin from build system: https://github.com/ublue-os/bluefin/commit/a3c2b039eb252c41c7ccd44ae8cd7c726c5742d9
- [x]  Cleanup bluefin system files: https://github.com/ublue-os/bluefin/commit/dbbc685d6f8200ba76fedce0ddaa1876bbb30df0
- [ ] Cleanup bluefin/gnome stuff in changelogs [changelogs.py](https://github.com/ublue-os/aurora/blob/main/.github/changelogs.py)
- [ ] Anywhere else in the Project

Bluefin commits are provided as reference, I also thought about putting the readme/other documentation here but that might be worth opening another issue

### LINKED ISSUE #35: Rename bluefin-cli to aurora-cli
Outside of the name, it will execute the same `ujust` script.

### PR DESCRIPTION
**Pull request by nisel11**
close #20 
close #35 

This seems to remove all mentions of bluefin(except links), but it may have been done wrong somewhere and currently it's breaking pull requests #40 because it have their changes.
[Already builded](https://github.com/nisel11/aurora/actions/runs/12391452846) (It's showing red, but that's because of the signing image)
[Changelog test](https://github.com/nisel11/aurora/releases/tag/stable-20241216.1)

### CODE REVIEW

**Review by nicknamenamenick — APPROVED** [review]

**Comment by nicknamenamenick** [comment]
Thanks!

**Comment by nisel11** [comment]
> Thanks!

Thanks for approving my PR!
Do you know something about codename or Codacy Badge?

**Comment by nicknamenamenick** [comment]
> > Thanks!
> 
> Thanks for approving my PR! Do you know something about codename or Codacy Badge?

@castrojo might

**Comment by nisel11** [comment]
Codacy Badge is now not removed as #48 will fix it

**Review by nicknamenamenick — APPROVED** [review]

**Comment by NiHaiden** [comment]
Thank you so much for your contribution! Really appreciate it :heart:!

**Comment by nisel11** [comment]
nvidia :bomb:

**Pull request merged**
